### ISSUE TITLE
collections only respond to each instead of all of Enumerable

### ISSUE THREAD

**Issue by stim371** [chriswarren/desk#44]
I was trying to filter through a list of rules using a regex:

    client.rules.select { |r| /custom_string/ =~ r.name }

    # which yields a NoMethodError because it tries to call #name on 'raw'

But it looks like only `each` is implemented on top of the `entries` collection.

Could this get expanded to implement Enumerable?

**Comment by stim371** [comment]
I'd be interested in working on it when my schedule permits, but I'm not too familiar with Hashie or how it's used here.

Do you have an idea where you'd hook it in? Dump it into method_missing?

**Comment by chriswarren** [comment]
We just upgraded the version of Hashie. I haven't had a chance to look in to if this'll address any of your concerns, but if you have a chance do you want to check it out?

**Comment by chriswarren** [comment]
Closing this for now. If it's still an issue, please reopen.
