### ISSUE TITLE
RuntimeError: missing dependency for FaradayMiddleware::Deashify: undefined method `type' for class `Hashie::Mash'

### ISSUE THREAD

**Issue by ryanfelton** [chriswarren/desk#60]
When looking up a customer with email addresses or phone numbers that have a "type" associated with them, the gem fails to parse the response. 

```
Desk.create_customer(
    :first_name => "Joe",
    :last_name => "User",
    :emails => [{:type => "work", :value => "joe.user@example.org"}]
)
```
Yields this error: 

```RuntimeError: missing dependency for FaradayMiddleware::Deashify: undefined method `type' for class `Hashie::Mash'```

**Comment by ryanfelton** [comment]
This is also true for the request

```
> Desk.customer("123456789")
RuntimeError: missing dependency for FaradayMiddleware::Deashify: undefined method `type' for class `Hashie::Mash'
```

**Comment by ryanfelton** [comment]
I think it's related to an change in Hashie: 
https://github.com/intridea/hashie/commit/61fc9a9cbce3999df515f4f291135b51372789c4

**Comment by robins35** [comment]
Having the same problem here.

**Comment by robins35** [comment]
Fixed by locking hashie at 3.4.0

**Comment by P9GIT** [comment]
Yup, same problem here. Fixed by locking Hashie gem at 3.4.1. Methods "type" and "id" are removed in Hashie version >= 3.4.2.

**Comment by patakijv** [comment]
Can the fix from Afonso be merged and submitted to rubygems source?

**Comment by jwfearn** [comment]
+1 please merge Afonso's fix and update rubygems

**Comment by chriswarren** [comment]
Done. Very sorry for the delay on this.

**Comment by saverio-kantox** [comment]
Maybe it was just the `Mash.send :undef_method, :type` in https://github.com/chriswarren/desk/blob/master/lib/desk/deash.rb#L21 ?
