### ISSUE TITLE
Hashie fixed version giving conflicts

### ISSUE THREAD

**Issue by P9GIT** [chriswarren/desk#69]
Hi.

Back in issue #60 the Hashie gem was fixed to a specific version to avoid breakage in the desk gem.

This version fix is however causing fallout now where the Hashie gem continues to develop with breaking changes.

Specifically the version lock ion #60 is now causing a conflict inn our app with e.g. the Zendesk gem where Hashie version >=3.5.2 is demanded due to a bug fix involving the breaking changes in Hashie 3.5.2.

With every new Hashie version this problem of conflicts will increase.

Is there any chance for an update to allow Hashie >=3.5.2 support?

Best regards, Thomas Balsløv.

**Comment by chriswarren** [comment]
If you'd like to make a pull request with the necessary changes I'd be happy to pull it in. Please make sure the test suite passes. Thanks!

**Comment by thomasbalsloev** [comment]
Closing since we use official Desk.com gem.
